# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iHLp5obmPsopamuSUjG10u6IGkgXovY

# Phase 1
"""

import yfinance as yf
import pandas as pd
import numpy as np

def get_market_data(start_date="2015-01-01"):
    # Replaced DX-Y.NY with UUP (US Dollar Index ETF)
    tickers = ['GLD', '^GVZ', 'UUP', '^TNX']
    df = yf.download(tickers, start=start_date)['Close'].dropna()

    df['Gold_Return'] = np.log(df['GLD'] / df['GLD'].shift(1))
    df['Gold_Vol'] = df['^GVZ']
    df['USD_Index'] = df['UUP']
    df['Yield_10Y'] = df['^TNX']
    return df[['Gold_Return', 'Gold_Vol', 'USD_Index', 'Yield_10Y']].dropna()

# Test Tool 1
market_data = get_market_data()
print("Data Tool operational! Row count:", len(market_data))

"""# Phase 2"""

import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# 1. Standardize All Features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(market_data.values)

# 2. Build 30-Day Sequence Windows
# Target index: Gold_Vol is column index 1
LOOKBACK = 30
X, y = [], []
for i in range(len(scaled_data) - LOOKBACK):
    X.append(scaled_data[i : i + LOOKBACK])
    y.append(scaled_data[i + LOOKBACK, 1])

X = np.array(X)
y = np.array(y)

# 3. Sequential Train/Test Split (80% Train, 20% Test - No Shuffling)
train_size = int(len(X) * 0.8)
X_train = torch.tensor(X[:train_size], dtype=torch.float32)
X_test = torch.tensor(X[train_size:], dtype=torch.float32)
y_train = torch.tensor(y[:train_size], dtype=torch.float32).unsqueeze(1)
y_test = torch.tensor(y[train_size:], dtype=torch.float32).unsqueeze(1)

# 4. Define the GRU Neural Network Architecture
class GoldVolatilityGRU(nn.Module):
    def __init__(self, input_dim=4, hidden_dim=32):
        super().__init__()
        self.gru = nn.GRU(input_size=input_dim, hidden_size=hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        _, h = self.gru(x)
        return self.fc(h[-1])

model = GoldVolatilityGRU()
criterion = nn.L1Loss()  # MAE Loss (robust against outliers)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005)

# 5. Train Model (60 Epochs)
epochs = 60
print("Training PyTorch GRU Network...")
for epoch in range(1, epochs + 1):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        print(f"Epoch {epoch}/{epochs} - Loss (MAE): {loss.item():.4f}")

# 6. Evaluate Model Predictions
model.eval()
with torch.no_grad():
    predictions = model(X_test).numpy()

# Plot first 150 days of testing predictions vs ground truth
plt.figure(figsize=(10, 4))
plt.plot(y_test.numpy()[:150], label='Actual Volatility (Scaled)', color='blue')
plt.plot(predictions[:150], label='Predicted Volatility (Scaled)', color='orange', linestyle='--')
plt.title("Phase 2: Gold Volatility Model Test Performance")
plt.xlabel("Test Set Days")
plt.ylabel("Scaled Volatility")
plt.legend()
plt.show()

# ==============================================================================
# PHASES 3, 4 & 5: TOOL INTEGRATION AND WORKFLOW ORCHESTRATION
# ==============================================================================

# Tool 2: Volatility Inference Engine
def predict_next_day_volatility(raw_data, trained_model, scaler):
    # Select the most recent 30 trading days of features
    latest_30_days = raw_data.values[-LOOKBACK:]
    scaled_window = scaler.transform(latest_30_days)
    input_tensor = torch.tensor(scaled_window, dtype=torch.float32).unsqueeze(0)

    trained_model.eval()
    with torch.no_grad():
        scaled_pred = trained_model(input_tensor).item()

    # Unscale the prediction back to actual ^GVZ volatility index points
    dummy = np.zeros((1, 4))
    dummy[0, 1] = scaled_pred
    unscaled_pred = scaler.inverse_transform(dummy)[0, 1]

    return unscaled_pred, scaled_pred

# Tool 3: Automated Risk Assessment & Decision Engine
def evaluate_risk_level(predicted_gvz, current_gvz):
    diff = predicted_gvz - current_gvz

    if predicted_gvz >= 22.0 or diff > 2.0:
        risk_status = "HIGH RISK / VOLATILITY SPIKE WARNING"
        recommendation = "Reduce long position size; hedge portfolio using gold put options."
    elif predicted_gvz >= 16.0 or diff > 0.5:
        risk_status = "ELEVATED RISK"
        recommendation = "Monitor order book closely; tighten stop-loss thresholds."
    else:
        risk_status = "NORMAL / LOW RISK"
        recommendation = "Maintain standard position allocations."

    return risk_status, recommendation, diff

# Workflow Orchestrator (Main Agent Execution Controller)
def run_market_risk_agent():
    print("=== EXECUTING AUTONOMOUS MARKET RISK AGENT WORKFLOW ===")

    # 1. Execute Tool 1: Ingest Fresh Market Data
    df = get_market_data()
    current_gvz = df['Gold_Vol'].iloc[-1]
    latest_date = df.index[-1].strftime('%Y-%m-%d')
    print(f"[Tool 1 - Data Fetcher]: Data loaded successfully up to {latest_date}.")

    # 2. Execute Tool 2: Run Neural Model Inference
    pred_gvz, pred_scaled = predict_next_day_volatility(df, model, scaler)
    print(f"[Tool 2 - Neural Model]: Model prediction calculated (Scaled: {pred_scaled:.4f}).")

    # 3. Execute Tool 3: Apply Risk Rules & Decision Logic
    risk_status, recommendation, diff = evaluate_risk_level(pred_gvz, current_gvz)
    print(f"[Tool 3 - Risk Engine]: Policy rules applied successfully.")

    # 4. Generate Final Automated Output Report
    print("\n" + "="*55)
    print("         AUTONOMOUS GOLD RISK AGENT EXECUTIVE REPORT     ")
    print("="*55)
    print(f" Execution Date        : {latest_date}")
    print(f" Current Gold Vol (^GVZ): {current_gvz:.2f} points")
    print(f" Predicted 24h Vol     : {pred_gvz:.2f} points")
    print(f" Forecasted Shift      : {'+' if diff >= 0 else ''}{diff:.2f} points")
    print(f" Identified Risk Level : {risk_status}")
    print(f" Autonomous Action     : {recommendation}")
    print("="*55 + "\n")

# Run the complete Agent Workflow
run_market_risk_agent()

import requests

# ==============================================================================
# CONFIGURATION: TELEGRAM CREDENTIALS
# ==============================================================================
TELEGRAM_BOT_TOKEN = "8859986286:AAHNXLoesx0HWAcxgv5ie2UoN5YT7v9Lih8"
TELEGRAM_CHAT_ID = "1399391666"

# ==============================================================================
# TOOL 2: VOLATILITY INFERENCE ENGINE
# ==============================================================================
def predict_next_day_volatility(raw_data, trained_model, scaler):
    latest_30_days = raw_data.values[-LOOKBACK:]
    scaled_window = scaler.transform(latest_30_days)
    input_tensor = torch.tensor(scaled_window, dtype=torch.float32).unsqueeze(0)

    trained_model.eval()
    with torch.no_grad():
        scaled_pred = trained_model(input_tensor).item()

    dummy = np.zeros((1, 4))
    dummy[0, 1] = scaled_pred
    unscaled_pred = scaler.inverse_transform(dummy)[0, 1]

    return unscaled_pred, scaled_pred

# ==============================================================================
# TOOL 3: AUTOMATED RISK DECISION ENGINE
# ==============================================================================
def evaluate_risk_level(predicted_gvz, current_gvz):
    diff = predicted_gvz - current_gvz

    if predicted_gvz >= 22.0 or diff > 2.0:
        risk_status = "HIGH RISK / VOLATILITY SPIKE WARNING"
        recommendation = "Reduce long position size; hedge portfolio using gold put options."
    elif predicted_gvz >= 16.0 or diff > 0.5:
        risk_status = "ELEVATED RISK"
        recommendation = "Monitor order book closely; tighten stop-loss thresholds."
    else:
        risk_status = "NORMAL / LOW RISK"
        recommendation = "Maintain standard position allocations."

    return risk_status, recommendation, diff

# ==============================================================================
# TOOL 4: TELEGRAM ALERT DISPATCHER
# ==============================================================================
def send_telegram_alert(report_text, bot_token, chat_id):
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": report_text,
        "parse_mode": "Markdown"
    }
    try:
        response = requests.post(url, json=payload)
        if response.status_code == 200:
            print("[Tool 4 - Alert Dispatcher]: Telegram notification sent successfully!")
        else:
            print(f"[Tool 4 - Alert Dispatcher]: Failed to send. Error: {response.text}")
    except Exception as e:
        print(f"[Tool 4 - Alert Dispatcher]: Network error: {e}")

# ==============================================================================
# WORKFLOW ORCHESTRATOR (MAIN AGENT CONTROLLER)
# ==============================================================================
def run_market_risk_agent():
    print("=== EXECUTING AUTONOMOUS MARKET RISK AGENT WORKFLOW ===")

    # 1. Tool 1: Ingest Fresh Market Data
    df = get_market_data()
    current_gvz = df['Gold_Vol'].iloc[-1]
    latest_date = df.index[-1].strftime('%Y-%m-%d')
    print(f"[Tool 1 - Data Fetcher]: Data loaded up to {latest_date}.")

    # 2. Tool 2: Neural Model Inference
    pred_gvz, pred_scaled = predict_next_day_volatility(df, model, scaler)
    print(f"[Tool 2 - Neural Model]: Prediction calculated (Scaled: {pred_scaled:.4f}).")

    # 3. Tool 3: Apply Risk Policy Rules
    risk_status, recommendation, diff = evaluate_risk_level(pred_gvz, current_gvz)
    print(f"[Tool 3 - Risk Engine]: Policy rules applied.")

    # 4. Tool 4: Dispatch Telegram Alert
    message = (
        f"🚨 *AUTONOMOUS GOLD RISK REPORT* 🚨\n\n"
        f"📅 *Date:* `{latest_date}`\n"
        f"📊 *Current Gold Vol (^GVZ):* `{current_gvz:.2f}`\n"
        f"🔮 *Predicted 24h Vol:* `{pred_gvz:.2f}`\n"
        f"📈 *Forecasted Shift:* `{'+' if diff >= 0 else ''}{diff:.2f}` pts\n\n"
        f"⚠️ *Risk Level:* *{risk_status}*\n"
        f"💡 *Action:* {recommendation}"
    )
    send_telegram_alert(message, TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID)

# Execute the complete pipeline
run_market_risk_agent()
